export interface Course {
  id: string;
  code: string;
  title: string;
  credits: number;
  professor: string;
  department: string;
  rating: number;
  difficulty: number;
  workload: number;
  learningGain: number;
  reviewCount: number;
  description: string;
  schedule: string;
  prerequisites: string[];
  evaluationMethods: string[];
  numExams: number;
  numQuizzes: number;
  numAssignments: number;
}

export interface Review {
  id: string;
  studentName: string;
  isAnonymous: boolean;
  semester: string;
  difficulty: number;
  workload: number;
  learningGain: number;
  overall: number;
  comment: string;
  helpful: number;
}

export const mockCourses: Course[] = [
  // Computer Science
  {
    id: '1',
    code: 'CSCI 103',
    title: 'Introduction to Programming',
    credits: 4,
    professor: 'Dr. William G.J. Halfond',
    department: 'Computer Science',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Basic programming in C++. Control structures, functions, arrays, file I/O, structs/classes.',
    schedule: 'MWF 10:00-10:50 AM, F 2:00-3:50 PM (Lab)',
    prerequisites: [],
    evaluationMethods: ['Exams', 'Assignments', 'Labs', 'Final Project'],
    numExams: 2,
    numQuizzes: 0,
    numAssignments: 8
  },
  {
    id: '2',
    code: 'CSCI 104',
    title: 'Data Structures and Object Oriented Design',
    credits: 4,
    professor: 'Prof. Marco Paolieri',
    department: 'Computer Science',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Object-oriented programming. Data structures including lists, stacks, queues, trees, heaps, hash tables, and graphs.',
    schedule: 'TTh 11:00 AM-12:20 PM, W 2:00-3:50 PM (Lab)',
    prerequisites: ['CSCI 103'],
    evaluationMethods: ['Exams', 'Assignments', 'Labs'],
    numExams: 2,
    numQuizzes: 3,
    numAssignments: 6
  },
  {
    id: '3',
    code: 'CSCI 201',
    title: 'Principles of Software Development',
    credits: 4,
    professor: 'Dr. Jeffrey Miller',
    department: 'Computer Science',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Object-oriented paradigm for programming-in-the-large in Java; writing sophisticated programs with high-level features.',
    schedule: 'MWF 12:00-12:50 PM, T 2:00-3:50 PM (Lab)',
    prerequisites: ['CSCI 104'],
    evaluationMethods: ['Exams', 'Assignments', 'Group Project', 'Quizzes'],
    numExams: 2,
    numQuizzes: 4,
    numAssignments: 5
  },
  // Business
  {
    id: '4',
    code: 'BUAD 304',
    title: 'Organizational Behavior and Leadership',
    credits: 4,
    professor: 'Prof. Morgan W. McCall',
    department: 'Marshall School of Business',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Individual and group behavior in organizations; leadership, motivation, communication, decision-making.',
    schedule: 'TTh 2:00-3:20 PM',
    prerequisites: [],
    evaluationMethods: ['Exams', 'Case Studies', 'Participation', 'Group Project'],
    numExams: 2,
    numQuizzes: 0,
    numAssignments: 4
  },
  {
    id: '5',
    code: 'BUAD 307',
    title: 'Marketing Fundamentals',
    credits: 4,
    professor: 'Dr. Lisa Mann',
    department: 'Marshall School of Business',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Introduction to marketing management decisions regarding product, price, promotion, and distribution.',
    schedule: 'MWF 9:00-9:50 AM',
    prerequisites: [],
    evaluationMethods: ['Exams', 'Marketing Plan', 'Quizzes', 'Presentation'],
    numExams: 2,
    numQuizzes: 5,
    numAssignments: 3
  },
  // Engineering
  {
    id: '6',
    code: 'EE 109',
    title: 'Introduction to Embedded Systems',
    credits: 4,
    professor: 'Prof. Mark Redekopp',
    department: 'Electrical Engineering',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Embedded processor and memory organization; assembly and C programming; interrupts; digital I/O.',
    schedule: 'MWF 1:00-1:50 PM, Th 2:00-4:50 PM (Lab)',
    prerequisites: ['CSCI 103'],
    evaluationMethods: ['Exams', 'Labs', 'Final Project'],
    numExams: 2,
    numQuizzes: 2,
    numAssignments: 6
  },
  {
    id: '7',
    code: 'AME 150',
    title: 'Introduction to Aerospace and Mechanical Engineering',
    credits: 3,
    professor: 'Dr. Dan Erwin',
    department: 'Aerospace & Mechanical Engineering',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Introduction to aerospace and mechanical engineering through hands-on projects and case studies.',
    schedule: 'MWF 11:00-11:50 AM',
    prerequisites: [],
    evaluationMethods: ['Exams', 'Projects', 'Labs'],
    numExams: 2,
    numQuizzes: 0,
    numAssignments: 4
  },
  // Liberal Arts
  {
    id: '8',
    code: 'WRIT 150',
    title: 'Writing and Critical Reasoning',
    credits: 4,
    professor: 'Dr. Sarah Davis-Goff',
    department: 'Writing Program',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Expository writing course focusing on the creation of persuasive, well-reasoned arguments.',
    schedule: 'TTh 12:30-1:50 PM',
    prerequisites: [],
    evaluationMethods: ['Essays', 'Drafts', 'Participation', 'Final Portfolio'],
    numExams: 0,
    numQuizzes: 0,
    numAssignments: 6
  },
  {
    id: '9',
    code: 'PHIL 102',
    title: 'History of Philosophy: Medieval and Modern',
    credits: 4,
    professor: 'Prof. Janet Levin',
    department: 'Philosophy',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Survey of philosophical thought from Augustine through Kant, including medieval Islamic and Jewish philosophy.',
    schedule: 'TTh 9:30-10:50 AM',
    prerequisites: [],
    evaluationMethods: ['Exams', 'Papers', 'Participation'],
    numExams: 2,
    numQuizzes: 0,
    numAssignments: 3
  },
  // Psychology
  {
    id: '10',
    code: 'PSYC 100',
    title: 'Introduction to Psychology',
    credits: 4,
    professor: 'Dr. Sarah Feiter',
    department: 'Psychology',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Introduction to psychological science, including biological bases of behavior, perception, learning, memory, and cognition.',
    schedule: 'MWF 10:00-10:50 AM',
    prerequisites: [],
    evaluationMethods: ['Exams', 'Quizzes', 'Research Participation'],
    numExams: 3,
    numQuizzes: 6,
    numAssignments: 2
  },
  {
    id: '11',
    code: 'PSYC 274',
    title: 'Statistics in Psychology',
    credits: 4,
    professor: 'Prof. Rand Wilcox',
    department: 'Psychology',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Statistical methods for psychological research including probability, hypothesis testing, and regression.',
    schedule: 'TTh 11:00 AM-12:20 PM, F 1:00-2:50 PM (Lab)',
    prerequisites: ['PSYC 100', 'MATH 118'],
    evaluationMethods: ['Exams', 'Labs', 'Final Project'],
    numExams: 3,
    numQuizzes: 0,
    numAssignments: 8
  },
  // Sciences
  {
    id: '12',
    code: 'CHEM 105a',
    title: 'General Chemistry',
    credits: 4,
    professor: 'Dr. Thomas Bertolini',
    department: 'Chemistry',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Fundamental principles and laws of chemistry; laboratory work emphasizes quantitative procedures.',
    schedule: 'MWF 9:00-9:50 AM, T 2:00-4:50 PM (Lab)',
    prerequisites: ['MATH 118'],
    evaluationMethods: ['Exams', 'Labs', 'Quizzes'],
    numExams: 3,
    numQuizzes: 8,
    numAssignments: 10
  },
  {
    id: '13',
    code: 'BISC 220',
    title: 'General Biology: Cell Biology and Physiology',
    credits: 4,
    professor: 'Dr. Stephanie Mel',
    department: 'Biological Sciences',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Cellular structure and function, bioenergetics, molecular biology, genetics, and physiology.',
    schedule: 'TTh 12:30-1:50 PM, W 2:00-4:50 PM (Lab)',
    prerequisites: [],
    evaluationMethods: ['Exams', 'Labs', 'Quizzes'],
    numExams: 3,
    numQuizzes: 6,
    numAssignments: 8
  },
  // Mathematics
  {
    id: '14',
    code: 'MATH 125',
    title: 'Calculus I',
    credits: 4,
    professor: 'Prof. Cymra Haskell',
    department: 'Mathematics',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Limits, continuity, differentiation, integration, and applications.',
    schedule: 'MWF 8:00-8:50 AM, T 8:00-8:50 AM (Discussion)',
    prerequisites: ['MATH 118 or placement exam'],
    evaluationMethods: ['Exams', 'Homework', 'Quizzes'],
    numExams: 3,
    numQuizzes: 10,
    numAssignments: 12
  },
  {
    id: '15',
    code: 'MATH 126',
    title: 'Calculus II',
    credits: 4,
    professor: 'Dr. Larry Goldstein',
    department: 'Mathematics',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Techniques of integration, infinite series, parametric equations, polar coordinates.',
    schedule: 'MWF 11:00-11:50 AM, Th 11:00-11:50 AM (Discussion)',
    prerequisites: ['MATH 125'],
    evaluationMethods: ['Exams', 'Homework', 'Quizzes'],
    numExams: 3,
    numQuizzes: 10,
    numAssignments: 12
  },
  // Communications
  {
    id: '16',
    code: 'COMM 204',
    title: 'Communication and Social Science',
    credits: 4,
    professor: 'Prof. Patricia Riley',
    department: 'Annenberg School',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Introduction to communication research methods and social science approaches to communication.',
    schedule: 'TTh 2:00-3:20 PM',
    prerequisites: [],
    evaluationMethods: ['Exams', 'Research Project', 'Presentation'],
    numExams: 2,
    numQuizzes: 0,
    numAssignments: 4
  },
  // Cinema
  {
    id: '17',
    code: 'CTCS 190',
    title: 'Introduction to Cinema',
    credits: 4,
    professor: 'Prof. Drew Casper',
    department: 'School of Cinematic Arts',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Aesthetic, technological, and cultural development of cinema from its origins to the present.',
    schedule: 'MW 2:00-3:50 PM',
    prerequisites: [],
    evaluationMethods: ['Exams', 'Film Analysis Papers', 'Screenings'],
    numExams: 2,
    numQuizzes: 0,
    numAssignments: 3
  },
  // Economics
  {
    id: '18',
    code: 'ECON 203',
    title: 'Principles of Microeconomics',
    credits: 4,
    professor: 'Dr. John Strauss',
    department: 'Economics',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Individual choice, theory of the firm, market structure, resource allocation, government regulation.',
    schedule: 'TTh 9:30-10:50 AM',
    prerequisites: [],
    evaluationMethods: ['Exams', 'Problem Sets', 'Quizzes'],
    numExams: 2,
    numQuizzes: 4,
    numAssignments: 6
  },

  // Viterbi School of Engineering Courses
  {
    id: '21',
    code: 'EE 109',
    title: 'Introduction to Embedded Systems',
    credits: 4,
    professor: 'Prof. Mark Redekopp',
    department: 'Electrical Engineering',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Introduction to embedded systems programming using microcontrollers. C programming, hardware interfacing, and real-time systems.',
    schedule: 'TTh 2:00-3:20 PM, F 2:00-3:50 PM (Lab)',
    prerequisites: ['CSCI 103'],
    evaluationMethods: ['Exams', 'Labs', 'Projects'],
    numExams: 2,
    numQuizzes: 4,
    numAssignments: 8
  },
  {
    id: '22',
    code: 'EE 201',
    title: 'Linear Circuits',
    credits: 4,
    professor: 'Prof. Mahta Moghaddam',
    department: 'Electrical Engineering',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Analysis of linear circuits using Kirchhoff\'s laws, nodal analysis, and network theorems. AC and DC circuit analysis.',
    schedule: 'MWF 10:00-10:50 AM, T 2:00-3:50 PM (Lab)',
    prerequisites: ['MATH 126'],
    evaluationMethods: ['Exams', 'Labs', 'Homework'],
    numExams: 3,
    numQuizzes: 6,
    numAssignments: 10
  },
  {
    id: '23',
    code: 'AME 201',
    title: 'Statics',
    credits: 3,
    professor: 'Prof. Paul Ronney',
    department: 'Aerospace and Mechanical Engineering',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Analysis of forces and moments in static equilibrium. Free body diagrams, trusses, frames, and machines.',
    schedule: 'TTh 11:00 AM-12:20 PM',
    prerequisites: ['MATH 126', 'PHYS 151'],
    evaluationMethods: ['Exams', 'Homework', 'Quizzes'],
    numExams: 3,
    numQuizzes: 8,
    numAssignments: 12
  },
  {
    id: '24',
    code: 'AME 301',
    title: 'Dynamics',
    credits: 3,
    professor: 'Prof. Eva Kanso',
    department: 'Aerospace and Mechanical Engineering',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Kinematics and kinetics of particles and rigid bodies. Newton\'s laws, work-energy, and impulse-momentum methods.',
    schedule: 'MWF 1:00-1:50 PM',
    prerequisites: ['AME 201'],
    evaluationMethods: ['Exams', 'Homework'],
    numExams: 3,
    numQuizzes: 0,
    numAssignments: 10
  },
  {
    id: '25',
    code: 'ISE 225',
    title: 'Operations Research: Deterministic Models',
    credits: 3,
    professor: 'Prof. Jong-Shi Pang',
    department: 'Industrial and Systems Engineering',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Linear programming, network flows, integer programming, and dynamic programming. Optimization techniques for decision making.',
    schedule: 'TTh 2:00-3:20 PM',
    prerequisites: ['MATH 225'],
    evaluationMethods: ['Exams', 'Projects', 'Homework'],
    numExams: 2,
    numQuizzes: 4,
    numAssignments: 8
  },
  {
    id: '26',
    code: 'ISE 330',
    title: 'Introduction to Operations Research: Stochastic Models',
    credits: 3,
    professor: 'Prof. Suvrajeet Sen',
    department: 'Industrial and Systems Engineering',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Probability models, queuing theory, simulation, and stochastic optimization. Applications in manufacturing and service systems.',
    schedule: 'MWF 11:00-11:50 AM',
    prerequisites: ['ISE 225', 'MATH 225'],
    evaluationMethods: ['Exams', 'Projects', 'Simulation Labs'],
    numExams: 2,
    numQuizzes: 6,
    numAssignments: 6
  },
  {
    id: '27',
    code: 'BME 210',
    title: 'Introduction to Biomedical Engineering',
    credits: 3,
    professor: 'Prof. Ellis Meng',
    department: 'Biomedical Engineering',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Introduction to biomedical engineering principles. Medical devices, biomaterials, and physiological systems.',
    schedule: 'TTh 9:30-10:50 AM',
    prerequisites: ['MATH 126', 'PHYS 151'],
    evaluationMethods: ['Exams', 'Projects', 'Presentations'],
    numExams: 2,
    numQuizzes: 4,
    numAssignments: 6
  },
  {
    id: '28',
    code: 'BME 310',
    title: 'Biomedical Instrumentation',
    credits: 4,
    professor: 'Prof. Gerald Loeb',
    department: 'Biomedical Engineering',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Principles of biomedical instrumentation. Sensors, signal processing, and medical device design.',
    schedule: 'TTh 11:00 AM-12:20 PM, F 2:00-3:50 PM (Lab)',
    prerequisites: ['BME 210', 'EE 201'],
    evaluationMethods: ['Exams', 'Labs', 'Design Project'],
    numExams: 2,
    numQuizzes: 4,
    numAssignments: 8
  },
  {
    id: '29',
    code: 'CE 205',
    title: 'Statics',
    credits: 3,
    professor: 'Prof. Sami Masri',
    department: 'Civil and Environmental Engineering',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Analysis of forces and moments in static equilibrium. Structural analysis and design principles.',
    schedule: 'MWF 10:00-10:50 AM',
    prerequisites: ['MATH 126', 'PHYS 151'],
    evaluationMethods: ['Exams', 'Homework', 'Design Projects'],
    numExams: 3,
    numQuizzes: 6,
    numAssignments: 10
  },
  {
    id: '30',
    code: 'CE 308',
    title: 'Mechanics of Materials',
    credits: 3,
    professor: 'Prof. Lucio Soibelman',
    department: 'Civil and Environmental Engineering',
    rating: 0,
    difficulty: 0,
    workload: 0,
    learningGain: 0,
    reviewCount: 0,
    description: 'Stress and strain analysis, material properties, and failure theories. Design of structural elements.',
    schedule: 'TTh 2:00-3:20 PM',
    prerequisites: ['CE 205'],
    evaluationMethods: ['Exams', 'Homework', 'Lab Reports'],
    numExams: 3,
    numQuizzes: 4,
    numAssignments: 8
  }
];

export const mockReviews: { [courseId: string]: Review[] } = {
  '1': [
    {
      id: '1',
      studentName: 'Anonymous Trojan',
      isAnonymous: true,
      semester: 'Fall 2024',
      difficulty: 0,
      workload: 0,
      learningGain: 0,
      overall: 4,
      comment: 'Halfond is an excellent professor! The pace is challenging but manageable. Make sure to start the assignments early - they build on each other. The lab sessions are super helpful.',
      helpful: 23
    },
    {
      id: '2',
      studentName: 'John D.',
      isAnonymous: false,
      semester: 'Spring 2024',
      difficulty: 0,
      workload: 0,
      learningGain: 0,
      overall: 4,
      comment: 'This class sets you up perfectly for CSCI 104. The C++ concepts are essential and Halfond explains everything clearly. Attend lectures - his examples are better than the textbook.',
      helpful: 18
    },
    {
      id: '3',
      studentName: 'Anonymous Trojan',
      isAnonymous: true,
      semester: 'Fall 2023',
      difficulty: 0,
      workload: 0,
      learningGain: 0,
      overall: 4,
      comment: 'Definitely harder than expected coming from high school, but the TAs are amazing and office hours are very helpful. The final project was actually fun once I got the hang of it.',
      helpful: 31
    },
    {
      id: '4',
      studentName: 'Sarah M.',
      isAnonymous: false,
      semester: 'Spring 2023',
      difficulty: 0,
      workload: 0,
      learningGain: 0,
      overall: 4,
      comment: 'Great introductory course. Professor Halfond is very approachable and willing to help. The workload is reasonable if you stay on top of things.',
      helpful: 15
    },
    {
      id: '5',
      studentName: 'Mike T.',
      isAnonymous: false,
      semester: 'Fall 2022',
      difficulty: 0,
      workload: 0,
      learningGain: 0,
      overall: 5,
      comment: 'Best CS professor at USC! His lectures are engaging and he genuinely cares about student success. Do all the practice problems.',
      helpful: 42
    }
  ],
  '2': [
    {
      id: '1',
      studentName: 'Anonymous Trojan',
      isAnonymous: true,
      semester: 'Fall 2024',
      difficulty: 0,
      workload: 0,
      learningGain: 0,
      overall: 4,
      comment: 'Very challenging but rewarding. Start the assignments as soon as they\'re released. The concepts are crucial for technical interviews.',
      helpful: 34
    },
    {
      id: '2',
      studentName: 'Alex P.',
      isAnonymous: false,
      semester: 'Spring 2024',
      difficulty: 0,
      workload: 0,
      learningGain: 0,
      overall: 4,
      comment: 'Prof Paolieri is great! Lectures can be fast-paced but everything you need is covered. Office hours are essential.',
      helpful: 27
    },
    {
      id: '3',
      studentName: 'Anonymous Trojan',
      isAnonymous: true,
      semester: 'Fall 2023',
      difficulty: 0,
      workload: 0,
      learningGain: 0,
      overall: 3,
      comment: 'Tough class. Make sure you have a solid foundation from 103. The debugging can be frustrating but you learn a lot.',
      helpful: 19
    }
  ],
  '10': [
    {
      id: '1',
      studentName: 'Emma L.',
      isAnonymous: false,
      semester: 'Fall 2024',
      difficulty: 0,
      workload: 0,
      learningGain: 0,
      overall: 4,
      comment: 'Really interesting class! Dr. Feiter makes the material engaging. The exams are fair if you attend lectures and do the readings.',
      helpful: 56
    },
    {
      id: '2',
      studentName: 'Anonymous Trojan',
      isAnonymous: true,
      semester: 'Spring 2024',
      difficulty: 0,
      workload: 0,
      learningGain: 0,
      overall: 4,
      comment: 'Great GE option. The workload is very manageable and the content is actually applicable to everyday life.',
      helpful: 41
    },
    {
      id: '3',
      studentName: 'David K.',
      isAnonymous: false,
      semester: 'Fall 2023',
      difficulty: 0,
      workload: 0,
      learningGain: 0,
      overall: 4,
      comment: 'Enjoyed this class more than I expected. The research participation requirement is interesting.',
      helpful: 28
    },
    {
      id: '4',
      studentName: 'Anonymous Trojan',
      isAnonymous: true,
      semester: 'Spring 2023',
      difficulty: 0,
      workload: 0,
      learningGain: 0,
      overall: 4,
      comment: 'Solid intro class. Quizzes are straightforward. Just keep up with the reading.',
      helpful: 22
    }
  ]
};